### ISSUE TITLE
Add Prettier?

### ISSUE THREAD

**Issue by dignite** [mob-timer/mob-timer#20]
- We use single quotes and no semi-colons but I recommend skipping `.prettierrc` and going 100% with the default rules.
- I think we should add ESlint for prettier with all the rules set to warn, and merge the re-formatting in a separate PR. Easier to follow up in the future how it was configured.
- [Official arguments for "Why Prettier?"](https://prettier.io/docs/en/why-prettier.html)

**Comment by niklas-r** [comment]
You know I love Prettier ❤️ 

I think it's important that, when combining ESLint with Prettier, Prettier should have the last say. So we shouldn't have any conflicting rules between the two.

I think your proposed approach is a good one. As far as I know, It's hard to do it more granular than this since Prettier will apply all its changes at once. The only way to make it more granular would be to do it per file, but I don't see any benefit to doing that.
